name: Release

author: liblaf

description: The `release` action automates the process of creating a release on GitHub, including generating a changelog, formatting it, and uploading specified assets.

inputs:
  clobber:
    description: Recreate the release if it already exists
    required: false
    default: "false"
  files:
    description: Newline-delimited list of path globs for asset files to upload
    required: false
  prerelease:
    description: Mark the release as a prerelease
    required: false
    default: "false"
  repo:
    description: Repository name with owner
    required: false
    default: ${{ github.repository }}
  tag:
    description: Tag name
    required: true
  token:
    description: GitHub token
    required: false
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
